In [ ]:
import numpy as np

empty_array = np.empty((2, 2))
ones_array = np.ones((4, 2))
filled_array = np.full((3, 3), 7)
example_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(example_array)
ones_like_array = np.ones_like(example_array)
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)

print(empty_array)
print(ones_array)
print(filled_array)
print(zeros_like_array)
print(ones_like_array)
print(numpy_array_from_list)


[[4.95410812e-310 0.00000000e+000]
 [1.17175679e+251 6.61469101e-310]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
arr_range = np.arange(10, 50)
matrix_3x3 = np.arange(9).reshape(3, 3)
identity_matrix = np.eye(3)
random_array = np.random.random(30)
mean_random_array = random_array.mean()
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
zero_array = np.zeros(10)
zero_array[4] = 1
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
checkerboard_pattern = np.zeros((8, 8))
checkerboard_pattern[1::2, ::2] = 1
checkerboard_pattern[::2, 1::2] = 1

print(arr_range)
print(matrix_3x3)
print(identity_matrix)
print(mean_random_array)
print(min_value, max_value)
print(zero_array)
print(reversed_arr)
print(border_array)
print(checkerboard_pattern)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.4519203517659598
0.002598302451503609 0.99316605081856
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
subtraction = x - y
multiplication = x * 2
squared_elements = np.square(x)
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
concat_x_y = np.concatenate((x, y), axis=0)
concat_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

try:
    concat_x_v = np.concatenate((x, v), axis=1)
except Exception as e:
    error_message = str(e)

print(addition)
print(subtraction)
print(multiplication)
print(squared_elements)
print(dot_v_w, dot_x_v, dot_x_y)
print(concat_x_y)
print(concat_v_w)
print(error_message)


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
219 [29 77] [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
AB = np.dot(A, B)
BA = np.dot(B, A)
transpose_AB = np.transpose(AB)
transpose_BT_AT = np.dot(np.transpose(B), np.transpose(A))

A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
X = np.linalg.inv(A_eq).dot(B_eq)

print(identity_matrix)
print(AB)
print(BA)
print(transpose_AB)
print(transpose_BT_AT)
print(X)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]
[ 2.  1. -2.]
